export const restaurant =  {
    COOKING_SLOTS : 7,
    DELIVERY_TIME_PER_KM: 8,
    APPETIZER_SLOT_REQUIRED: 1,
    APPETIZER_TIME_REQUIRED_MINS: 17,
    MAIN_COURSE_SLOT_REQUIRED: 2,
    MAIN_COURSE_TIME_REQURIED_MINS: 29,
};

export const orderTypes = {
    MAIN_COURSE: 'M',
    APPETIZER: 'A'
};

export const MAX_ORDER_WAIT_TIME_MINS = 150;